site_name: "Bican Models Documentation"
theme:
  name: material
  palette:
    scheme: black
    primary: black
  logo: images/bican_logo.png
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2

nav:
  - Overview: index.md
  - Library Generation: index_library_generation.md
  - ANSRS: index_ansrs.md
  - GARS: index_gars.md

