site_name: "BICAN Knowledge Graph Models Documentation"
theme:
  name: material
  palette:
    scheme: default
    primary: white
  logo: images/bican_logo.png
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2

nav:
  - Overview: index.md
  - Models:
    - Library Generation: index_library_generation.md
    - Anatomical Structure: index_anatomical_structure.md
    - Genome Annotation: index_genome_annotation.md
    - Assertion Evidence: index_assertion_evidence.md
    - BKE Taxonomy: index_bke_taxonomy.md
  - Visualizations: 
    - Library Generation: library_generation.md
    - Anatomical Structure: anatomical_structure.md
    - Genome Annotation: genome_annotation.md
    - Assertion Evidence: assertion_evidence.md
    - BKE Taxonomy: bke_taxonomy.md
repo_url: https://github.com/brain-bican/models