site_name: "Bican Models Documentation"
theme:
  name: material
  palette:
    scheme: black
    primary: black
  logo: images/bican_logo.png
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2

nav:
  - Home: index.md

