site_name: "BICAN Models Documentation"
theme:
  name: material
  palette:
    scheme: default
    primary: white
  logo: images/bican_logo.png
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2

nav:
  - Overview: index.md
  - Library Generation: index_library_generation.md
  - AnSRS: index_ansrs.md
  - GARS: index_gars.md
  - Working with the Models: 
    - Library Generation: 
    - AnSRS: 
    - GARS:
  - Visualizations: 
    - Library Generation: 
    - AnSRS: ansrs.md
    - GARS: 
  
repo_url: https://github.com/brain-bican/models
extra_css:
  -style.css