site_name: "BICAN Knowledge Graph Models Documentation"
theme:
  name: material
  palette:
    scheme: default
    primary: white
  logo: images/bican_logo.png
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2

nav:
  - Overview: index.md
  - Models:
    - Library Generation: index_library_generation.md
    - AnSRS: index_ansrs.md
    - GARS: index_gars.md
  - Visualizations: 
    - Library Generation: library_generation.md
    - AnSRS: ansrs.md
    - GARS: gars.md
  
repo_url: https://github.com/brain-bican/models