name: generating other formats for assertion_evidence

on:
  push:
    branches:
      - main
    paths:
      - 'linkml-schema/assertion_evidence.yaml'


permissions:
  contents: write
  pull-requests: write

jobs:
  generate_from_reusable:
    uses: brain-bican/models/.github/workflows/reusable-generate_other_formats.yaml@main
    with:
      model_name: assertion_evidence
