name: generating other formats for genome_annotation

on:
  pull_request_target:
    types: [opened, synchronize]
    paths:
      - 'linkml-schema/genome_annotation.yaml'
      - 'linkml-schema/bican_biolink.yaml'
      - 'linkml-schema/bican_core.yaml'


permissions:
  contents: write
  pull-requests: write

jobs:
  generate_from_reusable:
    uses: brain-bican/models/.github/workflows/reusable-generate_other_formats.yaml@main
    with:
      model_name: genome_annotation