name: push to bkbit
# run when the workflow named 'generating other formats' completes on a branch named main.
on:
  push:
    branches:
      - main
    paths:
      - 'linkml-schema/'
  workflow_run:
    workflows: [generating other formats]
    types: 
      - completed 
    branches:
      - main


jobs:
  update:
    runs-on: ubuntu-latest
    # 'update' job will only run if the "generate other formats" workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Pushes to another repository
        uses: dmnemec/copy_file_to_another_repo_action@main

        env: 
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'models_py-autogen/kbmodel.py'
          destination_repo: 'brain-bican/bkbit'
          destination_folder: 'bkbit/models/'
          user_email: 'xspuja@gmail.com' # the GitHub user email associated with the API token secret.
          user_name: 'puja-trivedi' # the GitHub username associated with the API token secret.
          commit_message: "Updated kbmodel.py. Pushed from brain-bican/model repository"