name: push to bkbit
on:
  push:
    branches: [ notebook_additions ]


jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Pushes to another repository
        uses: puja-trivedi/models@notebook_additions
        env: 
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:

          source-directory: models_py-autogen/
          destination-github-username: 'puja-trivedi'
          destination-repository-name: 'bkbit'
          target-branch: main
          target-directory: bkbit/models/
          user-email: xspuja@gmail.com
          
          commit-message: "Updated kbmodel.py"