name: push pydantic gars to bkbit

on:
  push:
    paths:
      - 'models_py-autogen/gars.py' 

jobs:
  update_gars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Pushes to another repository
        uses: dmnemec/copy_file_to_another_repo_action@main

        env: 
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'models_py-autogen/gars.py'
          destination_repo: 'brain-bican/bkbit'
          destination_folder: 'bkbit/models/'
          user_email: 'xspuja@gmail.com' # the GitHub user email associated with the API token secret.
          user_name: 'puja-trivedi' # the GitHub username associated with the API token secret.
          commit_message: "pydantic version of gars model (gars.py) was updated. Pushed from brain-bican/model repository"