name: push to bkbit
on:
  # push:
  #   branches: [ notebook_additions ]
  workflow_run:
    workflows: [generating other formats]
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Pushes to another repository
        uses: dmnemec/copy_file_to_another_repo_action@main

        env: 
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'models_py-autogen/kbmodel.py'
          destination_repo: 'puja-trivedi/bkbit'
          destination_folder: 'bkbit/models/'
          user_email: 'xspuja@gmail.com'
          user_name: 'puja-trivedi'
          commit_message: "Updated kbmodel.py pushed from brain-bican/model repository"
