name: push to bkbit
on:
  push:
    branches: [ notebook_additions ]


jobs:
  build:
    runs-on: ubuntu-latest
    needs: generate

    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: puja-trivedi/models@notebook_additions
        env: 
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'models_py-autogen/kbmodel.py'
          destination-github-username: 'puja-trivedi'
          destination-repository-name: 'bkbit'
          user-email: xspuja@gmail.com
          target-branch: main