name: push pydantic models to bkbit

on:
  push:
    branches:
      - main
      - push_to_bkbit_workflow_20241202
    paths:
        - 'models_py-autogen/*.py'

jobs:
  create_bkbit_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Set up Git and cloning repository
        env:
          TARGET_REPO: brain-bican/bkbit
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name "puja-trivedi"
          git config --global user.email "xspuja@gmail.com"
          git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/$TARGET_REPO.git

      - name: Identify changed files
        id: files
        run: |
          echo "::set-output name=changed_files::$(git diff --name-only HEAD^ HEAD | grep '^models_py-autogen/' || true)"

      - name: Process each changed file
        if: steps.files.outputs.changed_files != ''
        env:
          CHANGED_FILES: ${{ steps.files.outputs.changed_files }}
          TARGET_REPO: brain-bican/bkbit
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          for file in $CHANGED_FILES; do
            # Extract filename without path
            filename=$(basename $file)
            branch_name="update_${filename%.*}_model"

            # Copy the file to the target repository
            cp $file bkbit/bkbit/models/$filename
            
            # Navigate to the target repository and create a branch
            cd bkbit
            git checkout -b $branch_name

            # Stage changes and commit
            git add bkbit/models/$filename
            git commit -m "Updated $filename model is being copied and pushed from brain-bican/models repository."
            
            # Push changes to the new branch
            git push origin $branch_name
            
            # Create a pull request
            curl -X POST -H "Authorization: token $PERSONAL_ACCESS_TOKEN" \
              -d "{\"title\":\"Automated PR: Update $filename model.\", \"head\":\"$branch_name\", \"base\":\"main\"}" \
              https://api.github.com/repos/$TARGET_REPO/pulls
            
            # Navigate back to the root directory
            cd ..
          done
