name: generating other formats for multiple models for the specific linkml version

on:
  workflow_dispatch:
    inputs:
      linkml_version:
        description: 'linkml version to test'
        required: true
        type: string

permissions:
  contents: write

jobs:
  generate_from_reusable:
    uses: brain-bican/models/.github/workflows/reusable-generate_other_formats.yaml@main
    with:
      model_name: genome_annotation,library_generation,anatomical_structure,assertion_evidence
      linkml_version: ${{ github.event.inputs.linkml_version }}
