name: test generating other formats

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install the required python packages
        run: python -m pip install .[test]

      - name: Other installations
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget curl

      - name: Generate other model representations
        run: |
          cd linkml-schema
          for file in *.yaml; do
            if [ "$file" != "bican_biolink.yaml" ]; then
              name=`basename ${file} .yaml`;
              echo "Processing $name file..";
              # generating json schema
              gen-json-schema  ${file};
              # generating jsonld context
              gen-jsonld-context ${file};
              # generating pydantic schema
              gen-pydantic --pydantic-version 2 ${file};
              if [ ${name} != "kbmodel" ]; then
                gen-erdiagram ${file};
              fi
            fi
          done
          cd ..

